trigger:
  - main

pool:
  name: report S.K 
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Dependencies'

  - script: |
      python main.py
    displayName: 'Run Main Script'

  - script: |
      pytest test_app.py
    displayName: 'Run Tests'
